name: Java CI con Maven y JaCoCo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setear Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar, testear y generar reporte JaCoCo
        run: mvn clean verify

      - name: Subir reporte JaCoCo como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-jacoco
          path: target/site/jacoco
